# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Auto-generated Dockerfile for flight_mcp_server
FROM python:3.10-slim

# Install system dependencies for scraping and Playwright
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        gcc libffi-dev \
        wget ca-certificates \
        libnss3 libatk1.0-0 libatk-bridge2.0-0 libdrm2 libxkbcommon0 \
        libxcomposite1 libxrandr2 libgbm1 libgtk-3-0 libpango-1.0-0 libasound2 libx11-xcb1 libxcb1 libxdamage1 && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy Python dependency files
COPY pyproject.toml requirements.txt ./

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install Playwright browsers
RUN python3 -m playwright install --with-deps chromium

# Copy the rest of the application
COPY . .

# Ensure main.py is executable
RUN chmod +x main.py

# Use stdio transport; no HTTP port needed
CMD ["python3", "main.py"]
